[phases.setup]
nixPkgs = ["...", "php84Extensions.soap", "php84Extensions.xml", "php84Extensions.openssl", "php84Extensions.bcmath"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --ignore-platform-reqs"]
